# Secrets Management Configuration
apiVersion: v1
kind: Secret
metadata:
  name: monorepo-polyglot-secrets
  namespace: monorepo-polyglot
  labels:
    app.kubernetes.io/name: monorepo-polyglot
    app.kubernetes.io/version: "1.0.0"
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # Use: echo -n "your-secret" | base64
  
  # Database
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: Y2hhbmdlX21l  # change_me
  
  # JWT
  JWT_SECRET: Y2hhbmdlX21lX3RvX3NlY3VyZV9yYW5kb21fc3RyaW5n  # change_me_to_secure_random_string
  
  # API Keys
  STRIPE_SECRET_KEY: c2tfbGl2ZV9jaGFuZ2VfbWU=  # sk_live_change_me
  STRIPE_PUBLISHABLE_KEY: cGtfbGl2ZV9jaGFuZ2VfbWU=  # pk_live_change_me
  OPENAI_API_KEY: c2stY2hhbmdlX21l  # sk-change_me
  
  # Email
  SMTP_USER: bm9yZXBseUB5b3VyZG9tYWluLmNvbQ==  # noreply@yourdomain.com
  SMTP_PASS: Y2hhbmdlX21l  # change_me
  
  # Redis
  REDIS_PASSWORD: ""  # Empty if no password
  
---
# External Secrets Operator Configuration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: monorepo-polyglot
spec:
  provider:
    vault:
      server: "https://vault.yourdomain.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "monorepo-polyglot"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: monorepo-polyglot-external-secrets
  namespace: monorepo-polyglot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: monorepo-polyglot-secrets
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: database
      property: username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: database
      property: password
  - secretKey: JWT_SECRET
    remoteRef:
      key: auth
      property: jwt_secret
  - secretKey: STRIPE_SECRET_KEY
    remoteRef:
      key: payment
      property: stripe_secret_key
  - secretKey: STRIPE_PUBLISHABLE_KEY
    remoteRef:
      key: payment
      property: stripe_publishable_key
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: ai
      property: openai_api_key
  - secretKey: SMTP_USER
    remoteRef:
      key: email
      property: smtp_user
  - secretKey: SMTP_PASS
    remoteRef:
      key: email
      property: smtp_pass
