apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: monorepo-polyglot
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-service
        app.kubernetes.io/version: "1.0.0"
    spec:
      containers:
      - name: auth-service
        image: monorepo-polyglot/auth-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        envFrom:
        - configMapRef:
            name: monorepo-polyglot-config
        - secretRef:
            name: monorepo-polyglot-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
