apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monorepo-polyglot-ingress
  namespace: monorepo-polyglot
  labels:
    app.kubernetes.io/name: monorepo-polyglot
    app.kubernetes.io/version: "1.0.0"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://yourdomain.com,https://admin.yourdomain.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - yourdomain.com
    - admin.yourdomain.com
    - api.yourdomain.com
    secretName: monorepo-polyglot-tls
  rules:
  # Web App
  - host: yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 3000
  # Admin Panel
  - host: admin.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin-service
            port:
              number: 3001
  # API Gateway
  - host: api.yourdomain.com
    http:
      paths:
      # Auth Service
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 3002
      # Payment Service
      - path: /payment
        pathType: Prefix
        backend:
          service:
            name: payment-service
            port:
              number: 8080
      # Analytics Service
      - path: /analytics
        pathType: Prefix
        backend:
          service:
            name: analytics-service
            port:
              number: 8081
      # AI Service
      - path: /ai
        pathType: Prefix
        backend:
          service:
            name: ai-service
            port:
              number: 8082
      # PDF Service
      - path: /pdf
        pathType: Prefix
        backend:
          service:
            name: pdf-service
            port:
              number: 8083
