apiVersion: v1
kind: Namespace
metadata:
  name: monorepo-polyglot
  labels:
    name: monorepo-polyglot
    app.kubernetes.io/name: monorepo-polyglot
    app.kubernetes.io/version: "1.0.0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monorepo-polyglot-quota
  namespace: monorepo-polyglot
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: monorepo-polyglot-limits
  namespace: monorepo-polyglot
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
