apiVersion: v1
kind: Secret
metadata:
  name: monorepo-polyglot-secrets
  namespace: monorepo-polyglot
  labels:
    app.kubernetes.io/name: monorepo-polyglot
    app.kubernetes.io/version: "1.0.0"
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # Use: echo -n "your-secret" | base64
  
  # Database
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: Y2hhbmdlX21l  # change_me
  
  # JWT
  JWT_SECRET: Y2hhbmdlX21lX3RvX3NlY3VyZV9yYW5kb21fc3RyaW5n  # change_me_to_secure_random_string
  
  # API Keys
  STRIPE_SECRET_KEY: c2tfbGl2ZV9jaGFuZ2VfbWU=  # sk_live_change_me
  STRIPE_PUBLISHABLE_KEY: cGtfbGl2ZV9jaGFuZ2VfbWU=  # pk_live_change_me
  OPENAI_API_KEY: c2stY2hhbmdlX21l  # sk-change_me
  
  # Email
  SMTP_USER: bm9yZXBseUB5b3VyZG9tYWluLmNvbQ==  # noreply@yourdomain.com
  SMTP_PASS: Y2hhbmdlX21l  # change_me
  
  # Redis
  REDIS_PASSWORD: ""  # Empty if no password
  
---
# Separate secret for database connection
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: monorepo-polyglot
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: Y2hhbmdlX21l  # change_me
  database: bW9ub3JlcG9fcHJvZA==  # monorepo_prod
