# Secret Detection Configuration
rules:
  # API Keys
  - id: api-key
    pattern: '(?i)(api[_-]?key|apikey|access[_-]?key|secret[_-]?key)\s*[:=]\s*["\']?([a-zA-Z0-9_-]{20,})["\']?'
    severity: HIGH
    message: "Potential API key detected"

  # JWT Tokens
  - id: jwt-token
    pattern: 'eyJ[a-zA-Z0-9_-]*\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9_-]*'
    severity: MEDIUM
    message: "JWT token detected"

  # Database URLs
  - id: database-url
    pattern: '(?i)(postgresql|mysql|mongodb)://[^:\s]+:[^@\s]+@[^/\s]+/[^\s]+'
    severity: HIGH
    message: "Database connection string with credentials detected"

  # AWS Keys
  - id: aws-key
    pattern: 'AKIA[0-9A-Z]{16}'
    severity: HIGH
    message: "AWS access key detected"

  # Private Keys
  - id: private-key
    pattern: '-----BEGIN (RSA |DSA |EC |OPENSSH )?PRIVATE KEY-----'
    severity: HIGH
    message: "Private key detected"

  # Passwords
  - id: password
    pattern: '(?i)(password|passwd|pwd)\s*[:=]\s*["\']?([^"\'\s]{8,})["\']?'
    severity: MEDIUM
    message: "Password detected"

  # OAuth Tokens
  - id: oauth-token
    pattern: 'ya29\.[a-zA-Z0-9_-]+'
    severity: HIGH
    message: "OAuth token detected"

  # Slack Tokens
  - id: slack-token
    pattern: 'xox[baprs]-[0-9a-zA-Z-]+'
    severity: HIGH
    message: "Slack token detected"

  # GitHub Tokens
  - id: github-token
    pattern: 'ghp_[a-zA-Z0-9]{36}'
    severity: HIGH
    message: "GitHub token detected"

  # Stripe Keys
  - id: stripe-key
    pattern: 'sk_live_[a-zA-Z0-9]{24}'
    severity: HIGH
    message: "Stripe live key detected"

# Exclude patterns
exclude:
  - "*.test.js"
  - "*.spec.js"
  - "*.test.ts"
  - "*.spec.ts"
  - "test_*.py"
  - "*_test.go"
  - "Test*.java"
  - "node_modules/**"
  - ".git/**"
  - "dist/**"
  - "build/**"
  - "target/**"
